
import React from 'react';
import { DiagramBlock, Arrow, ConnectorLine } from '../DiagramCommon';

export const WorldModelDiagram: React.FC = () => {
  return (
    <div className="flex flex-col items-center space-y-6 p-4 bg-slate-900/50 rounded-lg text-xs">
      <div className="text-center mb-2 text-rose-300 font-semibold">World Model for Model-Based RL</div>

      {/* Main Loop: Agent-Environment Interaction */}
      <div className="flex justify-around w-full items-center">
        <DiagramBlock title="Environment (Real World)" color="rose-700" />
        <div className="flex flex-col items-center">
            <Arrow direction="right" label="Observation (o_t)" />
            <Arrow direction="left" label="Action (a_t)" className="mt-2"/>
        </div>
        <DiagramBlock title="Agent" color="rose-600" className="p-4 border border-dashed border-rose-400"/>
      </div>
      
      <div className="text-rose-300 font-medium my-2">Inside the Agent: The World Model Components</div>

      {/* Components of the World Model within the Agent */}
      <div className="flex flex-col items-center space-y-3 p-3 border border-rose-500 rounded-lg w-full max-w-2xl">
        {/* Vision Model (V) - VAE */}
        <DiagramBlock title="1. Vision Model (V): VAE" details="Observation (o_t) -> Latent State (z_t)" color="rose-500" />
        <Arrow direction="down" label="z_t (Compressed representation)" />

        {/* Memory Model (M) - MDN-RNN */}
        <DiagramBlock title="2. Memory Model (M): MDN-RNN" details="Predicts z_{t+1} from (z_t, a_t, h_t)" color="rose-500" />
        <div className="flex items-center space-x-1">
            <small className="text-rose-400">Inputs: current z_t, action a_t, hidden state h_t</small>
        </div>
        <Arrow direction="down" label="Predicted Next Latent State (z_{t+1})" />
        <div className="text-center text-sm text-slate-400"> (This forms the "Dream Environment") </div>
        
        {/* Controller (C) */}
        <DiagramBlock title="3. Controller (C): Small NN" details="Action (a_t) from (z_t, h_t)" color="rose-500" />
         <div className="flex items-center space-x-1">
            <small className="text-rose-400">Inputs: current z_t (from VAE or predicted by RNN), hidden state h_t</small>
        </div>
      </div>
      
      <div className="text-center mt-4">
        <p className="text-slate-300">
          Controller is trained either in the <strong className="text-rose-300">real environment</strong> (less sample efficient) 
          or <strong className="text-rose-300">within the "dream"</strong> generated by V and M (more sample efficient).
        </p>
        <Arrow direction="down" label="To Maximize Expected Reward" />
        <DiagramBlock title="Goal: Solve Task" color="rose-700" />
      </div>
    </div>
  );
};
